//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/DefaultActionaSSET.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DefaultActionaSSET: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DefaultActionaSSET()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DefaultActionaSSET"",
    ""maps"": [
        {
            ""name"": ""DefaultInputActionMap"",
            ""id"": ""e8b17dd7-a974-4b25-9755-6f35366d01a0"",
            ""actions"": [
                {
                    ""name"": ""MovementX"",
                    ""type"": ""Value"",
                    ""id"": ""0ffdfda4-e468-442d-8d51-8934fe0cb97b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MovementY"",
                    ""type"": ""Value"",
                    ""id"": ""83689081-88c8-482f-af7e-048e29eff0f0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Lamp"",
                    ""type"": ""Button"",
                    ""id"": ""664cc064-aec1-4064-aa2a-5e736aa6075b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Value"",
                    ""id"": ""07935fd5-11ef-48de-a6e4-1fbbee4bc45f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Button"",
                    ""id"": ""76c9f31d-e510-40c7-be8b-d992ec80ba31"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Axes"",
                    ""id"": ""b3ec7708-b1cd-44de-a837-583dd6099473"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""f23a2cd1-8d1b-49b4-8418-fd1e52ffdab8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""cc2a2ff0-8672-4d51-9140-c6193c80aa18"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Y"",
                    ""id"": ""5431143a-e541-4cda-881a-6bb29a21c22a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""244633c3-18e5-4e9b-87b0-12c13b3c0311"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b4580467-5caf-4228-8d09-d40e49ed73a6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7e26a9ba-5a0d-418f-a89e-bfb7eac01ae6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lamp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3c7645e-8480-46d7-bbee-6c53c9a27cff"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""041a2ad2-a464-45b4-8096-8fa7bf00737d"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebcc79ae-4b36-449d-9b39-139f559a95b7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": ""Scale"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3948f11-58f7-4d7f-9f7b-b3f5744ea827"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=2)"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba4a84c0-8744-41b9-85ec-e61e80705315"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=3)"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10455987-3eb5-43c1-8852-982eb2b846c8"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=4)"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DefaultInputActionMap
        m_DefaultInputActionMap = asset.FindActionMap("DefaultInputActionMap", throwIfNotFound: true);
        m_DefaultInputActionMap_MovementX = m_DefaultInputActionMap.FindAction("MovementX", throwIfNotFound: true);
        m_DefaultInputActionMap_MovementY = m_DefaultInputActionMap.FindAction("MovementY", throwIfNotFound: true);
        m_DefaultInputActionMap_Lamp = m_DefaultInputActionMap.FindAction("Lamp", throwIfNotFound: true);
        m_DefaultInputActionMap_Click = m_DefaultInputActionMap.FindAction("Click", throwIfNotFound: true);
        m_DefaultInputActionMap_Movement = m_DefaultInputActionMap.FindAction("Movement", throwIfNotFound: true);
    }

    ~@DefaultActionaSSET()
    {
        UnityEngine.Debug.Assert(!m_DefaultInputActionMap.enabled, "This will cause a leak and performance issues, DefaultActionaSSET.DefaultInputActionMap.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DefaultInputActionMap
    private readonly InputActionMap m_DefaultInputActionMap;
    private List<IDefaultInputActionMapActions> m_DefaultInputActionMapActionsCallbackInterfaces = new List<IDefaultInputActionMapActions>();
    private readonly InputAction m_DefaultInputActionMap_MovementX;
    private readonly InputAction m_DefaultInputActionMap_MovementY;
    private readonly InputAction m_DefaultInputActionMap_Lamp;
    private readonly InputAction m_DefaultInputActionMap_Click;
    private readonly InputAction m_DefaultInputActionMap_Movement;
    public struct DefaultInputActionMapActions
    {
        private @DefaultActionaSSET m_Wrapper;
        public DefaultInputActionMapActions(@DefaultActionaSSET wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovementX => m_Wrapper.m_DefaultInputActionMap_MovementX;
        public InputAction @MovementY => m_Wrapper.m_DefaultInputActionMap_MovementY;
        public InputAction @Lamp => m_Wrapper.m_DefaultInputActionMap_Lamp;
        public InputAction @Click => m_Wrapper.m_DefaultInputActionMap_Click;
        public InputAction @Movement => m_Wrapper.m_DefaultInputActionMap_Movement;
        public InputActionMap Get() { return m_Wrapper.m_DefaultInputActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultInputActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultInputActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultInputActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultInputActionMapActionsCallbackInterfaces.Add(instance);
            @MovementX.started += instance.OnMovementX;
            @MovementX.performed += instance.OnMovementX;
            @MovementX.canceled += instance.OnMovementX;
            @MovementY.started += instance.OnMovementY;
            @MovementY.performed += instance.OnMovementY;
            @MovementY.canceled += instance.OnMovementY;
            @Lamp.started += instance.OnLamp;
            @Lamp.performed += instance.OnLamp;
            @Lamp.canceled += instance.OnLamp;
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
        }

        private void UnregisterCallbacks(IDefaultInputActionMapActions instance)
        {
            @MovementX.started -= instance.OnMovementX;
            @MovementX.performed -= instance.OnMovementX;
            @MovementX.canceled -= instance.OnMovementX;
            @MovementY.started -= instance.OnMovementY;
            @MovementY.performed -= instance.OnMovementY;
            @MovementY.canceled -= instance.OnMovementY;
            @Lamp.started -= instance.OnLamp;
            @Lamp.performed -= instance.OnLamp;
            @Lamp.canceled -= instance.OnLamp;
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
        }

        public void RemoveCallbacks(IDefaultInputActionMapActions instance)
        {
            if (m_Wrapper.m_DefaultInputActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultInputActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultInputActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultInputActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultInputActionMapActions @DefaultInputActionMap => new DefaultInputActionMapActions(this);
    public interface IDefaultInputActionMapActions
    {
        void OnMovementX(InputAction.CallbackContext context);
        void OnMovementY(InputAction.CallbackContext context);
        void OnLamp(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
    }
}
